service: system-hp

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: personal-account

functions:
  sendEmail:
    handler: src/functions/sendMail/handler.sendEmail
    events:
      - http:
          path: /send
          method: post
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
